version: "3"

services:

  chrome:
    image: selenium/standalone-chrome:3.141
    ports:
      - "4444:4444"
    expose:
      - 4444
    volumes:
      - /dev/shm:/dev/shm

  sonarqube:
    image: sonarqube:7.9-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonar-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    depends_on:
      - sonar-db

  sonar-db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  postgresql:
  postgresql_data:
